
GET http://localhost:4201/login-page/

###
GET http://localhost:4201/login-page/203012


###

POST http://localhost:4201/login-page
Content-Type: application/json

{
    "name":"aksita", 
    "regno":"cse20305",
    "email":"aksita1@gmail.com",
    "pwd":"abcd"
}

###

DELETE http://localhost:4201/login-page/rajuuu@gmail.com


###

PATCH http://localhost:4201/login-page/cse20305
Content-Type: application/json

{
    "name":"aks"
}

###

GET http://localhost:4201/login-page/cse20310/abcde