
GET http://localhost:4201/login-page/

###
GET http://localhost:4201/login-page/203012


###

POST http://localhost:4201/login-page/:name/:regno/:email/:pwd

###

PUT http://localhost:4201/login-page/:email/:currentPassword/:newPassword


###

DELETE http://localhost:4201/login-page/:email


###

PATCH http://localhost:4201/login-page/cse20305
Content-Type: application/json

{
    "name":"aks"
}

###

GET http://localhost:4201/login-page/cse20310/abcde