
GET http://localhost:4201/canteen


###

GET http://localhost:4201/canteen/:category/:canteenname

###


GET http://localhost:4201/canteen/business/lunch

###

GET http://localhost:4201/canteen/business/dinner

###

GET http://localhost:4201/canteen/it/breakfast

###

GET http://localhost:4201/canteen/it/lunch

###

GET http://localhost:4201/canteen/it/dinner

###

POST http://localhost:4201/canteen
Content-Type: application/json

{
      "foodid" : 150,
      "name": "lemon sadham",
      "price": 5.99,
      "description": "Tdosa with chutny and sambar",
      "category":"lunch",
      "canteenname":"business"
}

###

DELETE http://localhost:4201/canteen/main/dinner/128

###

PATCH http://localhost:4201/canteen/main/breakfast/128
Content-Type: application/json

{
    "name": "pasta",
    "description": "Updated description",
    "price": 10.99
}

