
GET http://localhost:4201/canteen
 

###

GET http://localhost:4201/canteen/:category/:canteenname

###

POST http://localhost:4201/canteen

###

DELETE http://localhost:4201/canteen/main/dinner/128

###

PATCH http://localhost:4201/canteen


###
PATCH http://localhost:4201/canteen/150/:exist_quantity
###

PATCH http://localhost:4201/canteen/:_id/:exist_quantity

###
#PATCH http://localhost:4201/canteen/646cf403fa23875ee1233a85/112

###

GET http://localhost:4201/canteen/cart/most-ordered

