
GET http://localhost:4201/login-page/

###
GET http://localhost:4201/login-page/:regno


###

POST http://localhost:4201/login-page/

###

#GET http://localhost:4201/login-page/203012/viji

###

PATCH http://localhost:4201/login-page/:email

{ 
    "name":"aks"
}

###

DELETE http://localhost:4201/login-page/srini6703@gmail.com
###

PUT http://localhost:4201/login-page/:email/:currentPassword/:newPassword

###
#forgotpwd
POST http://localhost:4201/login-page/:email


###

GET http://localhost:4201/login-page/:id/:token


###

POST http://localhost:4201/login-page/:id/:token


###
#forgot pwd 

#hello
